DROP TABLE companies;
CREATE TABLE IF NOT EXISTS MyTable (Primary_Key INTEGER PRIMARY KEY,Text_Entry NVARCHAR(2048) NULL); 
CREATE TABLE IF NOT EXISTS companies(idNumbC INTEGER PRIMARY KEY, name TEXT NOT NULL);